name: Test Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  test-docker-compose:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: local
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - run: op run --env-file=".env" -- docker compose build
      - run: docker compose down -v --remove-orphans
      - run: op run --env-file=".env" -- docker compose up -d --wait backend frontend adminer
      - name: Test backend is up
        run: curl http://localhost:8000/api/v1/utils/health-check
      - name: Test frontend is up
        run: curl http://localhost:5173
      - run: docker compose down -v --remove-orphans
